# Generated by Django 5.2.1 on 2025-05-14 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='anuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comando', models.CharField(max_length=20, unique=True)),
                ('tipo_comando', models.CharField(choices=[('TODOS', 'Todos'), ('VIP', 'VIP'), ('MODERADOR', 'Moderador'), ('SUPERMOD', 'Supermod')], default='TODOS', max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('ejemplo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_twitch', models.CharField(choices=[('ELCILANTROUWU', 'elcilantrouwu'), ('JOSHUAKOMODO', 'joshuakomodo'), ('KEDOP_19', 'kedop_19'), ('MELODYZOMBIE', 'MelodyZombie'), ('MRPONCHO345', 'mrponcho345'), ('POIYUTE', 'PoiYuTe'), ('CHACHOYVT', 'ChachoyVT')], max_length=20, unique=True)),
                ('alias', models.CharField(default='', max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(default='changeme', max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
