# Generated by Django 5.2.1 on 2025-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comando', models.CharField(max_length=20, unique=True)),
                ('tipo_comando', models.CharField(choices=[('TODOS', 'Todos'), ('VIP', 'VIP'), ('MODERADOR', 'Moderador'), ('SUPERMOD', 'Supermod')], default='TODOS', max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('ejemplo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_twitch', models.CharField(choices=[('ELCILANTROUWU', 'elcilantrouwu'), ('JOSHUAKOMODO', 'joshuakomodo'), ('KEDOP_19', 'kedop_19'), ('MELODYZOMBIE', 'MelodyZombie'), ('MRPONCHO345', 'mrponcho345'), ('POIYUTE', 'PoiYuTe'), ('CHACHOYVT', 'ChachoyVT')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
