# Generated by Django 5.2.1 on 2025-07-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
