# Generated by Django 5.2.1 on 2025-07-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_moderador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='tipo_comando',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('VIP', 'VIP'), ('MODERATOR', 'Moderator'), ('SUPER_MODERATOR', 'Super Moderator')], default='TODOS', max_length=20),
        ),
    ]
