# Generated by Django 5.2.1 on 2025-07-14 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comando_tipo_comando'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='contenido',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
