# Generated by Django 5.2.1 on 2025-07-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anuncios_activo_anuncios_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas_Mods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('contenido', models.CharField(max_length=20000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream_WWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_stream', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Combate_WWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luchador_1', models.CharField(max_length=100)),
                ('luchador_2', models.CharField(max_length=100)),
                ('resultado', models.CharField(choices=[('VICTORIA', 'Victoria'), ('DERROTA', 'Derrota'), ('EMPATE', 'Empate'), ('NO_CONTEST', 'Sin Decisión')], max_length=20)),
                ('orden_combate', models.PositiveIntegerField(help_text='Orden del combate en el stream')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', to='core.stream_wwe')),
            ],
            options={
                'ordering': ['stream', 'orden_combate'],
            },
        ),
    ]
