# Generated by Django 5.2.1 on 2025-07-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notas_mods_stream_wwe_combate_wwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas_mods',
            name='categoria',
            field=models.CharField(choices=[('SUGERENCIAS', 'SUGERENCIAS'), ('BUGS', 'BUGS'), ('OTROS', 'OTROS')], default='OTROS', max_length=100),
        ),
        migrations.AddField(
            model_name='notas_mods',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAJA', 'BAJA')], default='BAJA', max_length=100),
        ),
    ]
