# Generated by Django 5.2.1 on 2025-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notas_mods_categoria_notas_mods_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate_wwe',
            name='luchador_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='combate_wwe',
            name='luchador_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='combate_wwe',
            name='tipo_combate',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PAREJAS', 'Parejas'), ('ESPECIAL', 'Especial')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='combate_wwe',
            name='luchador_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='combate_wwe',
            name='luchador_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='combate_wwe',
            name='resultado',
            field=models.CharField(choices=[('VICTORIA', 'Victoria'), ('DERROTA', 'Derrota'), ('EMPATE', 'Empate'), ('NO_CONTEST', 'Sin Decisión')], default='NO_CONTEST', max_length=20),
        ),
    ]
